INPUT_NEURONS = 9
HIDDEN_LAYER_1_NEURONS = 9
OUTPUT_NEURONS = 9

POPULATION_SIZE = 20
GENERATIONS = 100
MUTATION_RATE = 0.05
CROSSOVER_RATE = 0.8
ELITISM_COUNT = 2

MINIMAX_MEDIUM_THRESHOLD = 0.50
MINIMAX_HARD_THRESHOLD = 1.00

TRAINING_MODES_ORDER = ["medium", "hard"]

WIN_SCORE = 100
DRAW_SCORE = 10
LOSS_PENALTY = -50
INVALID_MOVE_PENALTY = -20

PLAYER_X = 1
PLAYER_O = -1
EMPTY_CELL = 0